[package]
name = "day1"
edition.workspace = true
version.workspace = true

[dependencies]
itertools = { workspace = true, features = [] }
maplit = { workspace = true, features = [] }
utilities = { path = "../utilities" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
