[workspace]
resolver = "2"
default-members = ["day1"]

members = [
    "day1",
    "day2",
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
itertools = "0.12.0"
maplit = "1.0.2"
